---

- name: Copy files from source to target.
  shell: "rsync {{ '--remove-source-files' if mysql_sync_delete_dump is defined else '' }} --delay-updates --compress --archive --out-format='{{changed_marker}}%i %n%L' {{hostvars[item.source + '.prod'].ansible_user|default(ansible_user)}}@{{hostvars[item.source + '.prod'].ansible_host}}:{{ mysql_sync_source_dump_dir }}/{{ item.database }}.sql.compressed {{ mysql_sync_dump_dir }}/{{ item.database }}.sql.compressed"
  check_mode: no
  with_items: "{{ mysql_sync_config }}"

- name: Extract dump on target.
  shell: >
    {{ mysql_sync_decompress_cmd | default(mysql_sync_default_compress_commands[mysql_sync_compress_method]['decompress_cmd']) }} {{ mysql_sync_decompress_args | default('') }}
    {{ mysql_sync_dump_dir }}/{{ item.database }}.sql.compressed > {{ mysql_sync_dump_dir }}/{{ item.database }}.sql
  check_mode: no
  with_items: "{{ mysql_sync_config }}"

- name: Drop database on target.
  mysql_db:
    name: "{{ item.0.target_database|default(item.0.database) }}"
    state: "{{ item.1 }}"
  with_nested:
    - "{{ mysql_sync_config }}"
    - [ absent, present ]

- name: Import database on target.
  mysql_db:
    name: "{{ item.target_database|default(item.database) }}"
    state: import
    target: "{{ mysql_sync_dump_dir }}/{{ item.database }}.sql"
  with_items: "{{ mysql_sync_config }}"
